# Generated by Django 5.2.1 on 2025-08-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'verbose_name': 'Perfil de Usuario', 'verbose_name_plural': 'Perfiles de Usuarios'},
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='id',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='id_personalizado',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
