# Generated by Django 5.2.1 on 2025-08-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_perfilusuario_options_remove_perfilusuario_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='apellido',
            field=models.CharField(default='SinApellido', max_length=100),
        ),
    ]
