# Generated by Django 5.2.1 on 2025-09-02 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_perfilusuario_apellido_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direccion',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='tipo',
        ),
    ]
