# Generated by Django 5.2.1 on 2025-08-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_delete_blogdisponible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='blog',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
