# Generated by Django 5.2.1 on 2025-08-08 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blog_descripcion_blog_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='show',
        ),
    ]
