# Generated by Django 5.2.1 on 2025-08-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blog_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='mostarBanner',
            field=models.BooleanField(default=False),
        ),
    ]
