# Generated by Django 5.2.7 on 2025-11-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_orden_mp_external_reference_orden_mp_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='numero_orden',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
