# Generated by Django 5.2.1 on 2025-07-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferretetia', '0002_producto_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precioDescuento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
