# Generated by Django 5.2.1 on 2025-07-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferretetia', '0003_producto_preciodescuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='sku',
            field=models.CharField(default=10, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
