# Generated by Django 5.2.1 on 2025-07-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferretetia', '0004_producto_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, default='ferretetia/default.jpg', upload_to='ferretetia/'),
        ),
    ]
