# Generated by Django 5.2.1 on 2025-07-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferretetia', '0005_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, default='images/default.jpg', upload_to='images/'),
        ),
    ]
