# Generated by Django 5.2.1 on 2025-07-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferretetia', '0006_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
