# Generated by Django 5.2.1 on 2025-07-31 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferretetia', '0008_categoria_alter_producto_options_producto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='imagen',
        ),
    ]
