# Generated by Django 5.2.1 on 2025-08-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferretetia', '0009_remove_categoria_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
