# Generated by Django 5.2.1 on 2025-08-06 16:51

from django.db import migrations, models
import django.db.models.deletion


def remove_session_carts(apps, schema_editor):
    """Eliminar todos los carritos que tienen session_key (usuarios anónimos)"""
    Carrito = apps.get_model('cart', 'Carrito')
    # Eliminar carritos que tienen session_key (usuarios anónimos)
    Carrito.objects.filter(session_key__isnull=False).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        # Primero eliminar los carritos de session_key
        migrations.RunPython(remove_session_carts, reverse_code=migrations.RunPython.noop),
        
        # Eliminar el campo session_key
        migrations.RemoveField(
            model_name='carrito',
            name='session_key',
        ),
        
        # Hacer el campo usuario obligatorio
        migrations.AlterField(
            model_name='carrito',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
